apiVersion: v1
kind: Deployment
metadata: 
    name: phpserver-deploy
spec: 
   selector: 
       matchLabels:
             app: phpserver
   template:
       metadata: 
           labels:
              app: phpserver
       spec:
         containers: 
            - name: phpserver
              image: vimal13/apache-webserver-php
              ports:
                - containerPort: 80
                  name: phpserver
              volumeMounts:
                - name: php-volume 
                  mountPath: /var/www/html
         volumes:
            - name: php-volume
              persistentVolumeClaim:
                  claimName: php-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: php-volume
spec: 
    accessModes:
        - ReadWriteOnce
    resources:
       requests:
           storage: 2Gi

---

apiVersion: v1
kind: Service
metadata: 
    name: php-service
    labels:
      app: php
spec:
    ports:
      - port: 80
    selector:
        app: php
    type: NodePort
   
                                   
 
  
      